### ISSUE TITLE
Configurable storage structure

### ISSUE THREAD

**Issue by VolkerHartmann** [kit-data-manager/metastore2#17]
Currently, all files for a resource are stored in a folder <METADATA_LOCATION>/<METADATA_ID>. If the repository is heavily used, huge numbers of resource may appear in the metadata folder affecting the file system performance. In order to avoid this situation, additional (configurable) hierarchy layers should be introduced instead of only using the year, e.g. year/month/day.

**Comment by VolkerHartmann** [comment]
Hierarchy layers by date will also not scale well if a repo has to ingest a bunch of entries e.g. at first time. I would prefer a hierarchy layer splitting the UUID in parts of 4 bytes each.
e.g.:
eaa0dc76-9597-41dc-8e29-2b0c18174753 --> eaa0/dc76/9597/41dc/8e29/2b0c/1817/eaa0dc76-9597-41dc-8e29-2b0c18174753

**Comment by tegx** [comment]
Instead of an UUID you could use the schema hash (you already calculating) and split it into n-byte pieces to introduce hierarchy layers. Drawback would be if you ever change the hashing algo, you need to migrate or maintain parallel ways.

**Comment by VolkerHartmann** [comment]
> Instead of an UUID you could use the schema hash (you already calculating) and split it into n-byte pieces to introduce hierarchy layers. Drawback would be if you ever change the hashing algo, you need to migrate or maintain parallel ways.
Right now the UUID is calculated anyway and it will not change by updating metadata.
