### ISSUE TITLE
Include git and build info for spring-boot actuator

### ISSUE THREAD

**Issue by ThomasJejkal** [kit-data-manager/metastore2#184]
**Is your feature request related to a problem? Please describe.**
Having an instance of a service running which behaves unexpected often raises the question, which version this service has and from which source (branch, commit) it was build. To deliver such information,  spring-boot offers an actuator endpoint at /actuator/info which contains no information by default. This should be changed for all services.

**Describe the solution you'd like**
Filling the info endpoint is quite easy as it only requires two modifications in build.gradle:

1. Add an additional plugin for obtaining Git information:
```
plugins { 
[...]
  id "com.gorylenko.gradle-git-properties" version "2.4.1"
[...]
}
```

2. Call an additional task for including build and Git information in the boot jar: 

```
springBoot {    
    buildInfo()
}
```

The second step assumes, that plugin "org.springframework.boot" is used.

The result may look as follows:

```
{
   "git":{
      "branch":"development",
      "commit":{
         "id":"6926cb7",
         "time":"2023-01-13T22:06:40Z"
      }
   },
   "build":{
      "artifact":"base-repo",
      "name":"base-repo",
      "time":"2023-01-17T21:21:27.413Z",
      "version":"1.2.1-SNAPSHOT"
   }
}
```

🎉 Nice, isn't it?

**Comment by VolkerHartmann** [comment]
Don't work like described with SpringBoot 2.7.7 and gradle 7.6!?
> Could not find method buildInfo() for arguments [] on task ':bootJar' of type org.springframework.boot.gradle.tasks.bundling.BootJar.
