### ISSUE TITLE
Internal URLs invalid if MetaStore runs behind proxy

### ISSUE THREAD

**Issue by ThomasJejkal** [kit-data-manager/metastore2#218]
**Describe the bug**
Running MetaStore behind a proxy may cause problems with internal URLs, e.g., schemaDocumentUri in SchemaRecord and metadataDocumentUri and schema.identifier in MetadataRecord. The issue was spotted while running MetaStore behind a Spring Cloud Gateway, but it might also be a problem for other ways of proxying.

**To Reproduce**
1. MetaStore is running at https://demo.datamanager.kit.edu:8040, such that a schema 'test' is accessible via https://demo.datamanager.kit.edu:8040/api/v1/schemas/test
2. A Spring Cloud Gateway is running at https://demo.datamanager.kit.edu:8443 forwarding all request via path /metastore to MetaStore, such that the resource from 1) is accessible via https://demo.datamanager.kit.edu:8443/metastore/api/v1/schemas/test
3. However, accessing the schema metadata will state, that schemaDocumentUri is https://demo.datamanager.kit.edu:8040/api/v1/schemas/test?version=1
4. Creating a metadata document makes things even worse, as schema.identifier is also pointing to the wrong schema location and also metadataDocumentUri does.

**Reason and Solution**
In MetaStore, Spring Boot HATEOAS functionality is used to determine internal URLs, e.g., 

```
URI resourceURI = WebMvcLinkBuilder.linkTo(WebMvcLinkBuilder.methodOn(this.getClass()).getById("test123", 1l, request,response)).toUri()
```
By default, information from the ServletContext is used to build the resulting URIs and the ServletContext is only aware of running at https://demo.datamanager.kit.edu:8040/. In order to communicate the actual endpoint a request was originally sent to, a proxy typically provides X-Forwarded-* Headers, e.g.

```
x-forwarded-proto: [https]
x-forwarded-prefix: [/base-repo]
x-forwarded-port: [443]
x-forwarded-host: [demo.datamanager.kit.edu:443]
```

These headers have to be processed to Spring Boot HATEOS, which is not the case by default. Processing can be enabled by adding a ForwardedHeaderFilter ([Source](https://docs.spring.io/spring-hateoas/docs/current/reference/html/#server.link-builder.forwarded-headers)), e.g., in the security configuration, as follows:

```
@Bean
ForwardedHeaderFilter forwardedHeaderFilter() {
    return new ForwardedHeaderFilter();
}
```

Afterwards, the headers are properly included while generating HATEOS links and the resulting URI points to the proxy and eventually added sub-paths.

**Comment by VolkerHartmann** [comment]
As of Spring Web 5.1, the ForwardedHeaderFilter has been deprecated in favor of the ForwardedHeaderTransformer. 
But there is an even easier way to get the 'X-Forwarded-...' headers.
Add this line to your 'application.properties' file:
server.forward-headers-strategy=framework
