### ISSUE TITLE
Expected performance issues with log level TRACE

### ISSUE THREAD

**Issue by ThomasJejkal** [kit-data-manager/metastore2#233]
In some classes, conditional logging on TRACE level may have a severe impact on performance for instances with many schemas/documents. Examples are: 

MetastoreOAIPMHRepository [492-498]
```
if (LOGGER.isTraceEnabled()) {
     LOGGER.trace("List all items:");
     List<DataRecord> findAll = dataRecordDao.findAll();
     for (DataRecord item : findAll) {
         LOGGER.trace("-> " + item);
      }
}
```

MetadataSchemaRecordUtil [708-714]
```
if (LOG.isTraceEnabled()) {
 LOG.trace("-----------------------------------------");
    url2PathDao.findAll().forEach((item) -> {
    LOG.trace("- {}", item);
    });
 LOG.trace("-----------------------------------------");
}
```

For sure, having TRACE logging enabled in production is not recommended anyways, but as soon as it is enabled for spotting issues, logging huge amounts of information may have other negative side effects and makes the log output useless.

**Found occurrences:** 

MetastoreOAIPMHRepository
MetadataSchemaRecordUtils
MetadataControllerImpl
SchemaRegistryControllerImpl

**Comment by VolkerHartmann** [comment]
I disagree slightly.
It is true that performance suffers greatly when the TRACE level is activated. However, it should only be enabled for precise debugging. Appropriate GUIs are capable of filtering it out so that you can concentrate on the essentials. I would rather have too many logs than miss information when troubleshooting.

**Comment by ThomasJejkal** [comment]
Of course, log analysis using a GUI (where applicable) could solve the issue with missing information. But still, on the server side performance is decreased remarkably as huge amounts of information might be fetched from the database and this may cause response errors due to long response times. I had this problem recently with repo-core, that's why I've opened this issue.
