### ISSUE TITLE
Schema version is increased when schema does not change

### ISSUE THREAD

**Issue by tegx** [kit-data-manager/metastore2#27]
When uploading a schema multiple times without changing the schema, the schema version is always increased. Additionally for every "new" version a new ACL entry is created. I would expect that the schema version and ACL entry stays the same if no changes in the schema are detected.

After a short investigation: The controller correctly detects that no changes occurred since it does not write the schema to the filesystem again. (Filesystem has only one version, whereas the version in the database is counted upwards with every upload.) Adjusting test case `testCreateTwoVersionsOfSchemaRecord` in `SchemaRegistryControllerTest` would detect this behavior.

Test environment:
```json
// schema
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://localhost:8040/api/v1/schemas/Test",
  "title": "Test",
  "type": "object",
  "properties": {
    "asd": {
      "type": "string"
    }
  }
}

// record
{"schemaId": "Test", "mimeType": "application/json", "type": "JSON"}

// curl
curl -X POST -H "Content-Type: multipart/form-data" -F "schema=@Test.json" -F "record=@record.json;type=application/json" http://localhost:8040/api/v1/schemas/
```

**Comment by ThomasJejkal** [comment]
Indeed, this behaviour is not optimal and may lead to confusion. For POST operations, it should be checked first if the schema is provided and has changed. If this is not the case, the call should be interpreted as PUT operation as this one is meant to be used for updating the schema record without increasing the version.
