### ISSUE TITLE
Support also version of schema during ingest of metadata document.

### ISSUE THREAD

**Issue by VolkerHartmann** [kit-data-manager/metastore2#30]
By default, a document should be linked to the latest version of a schema.
On the other hand, it should also be possible to link it to an older version, or 
to switch to the current version when updating the document.

**Comment by ThomasJejkal** [comment]
I fully agress, especially due to the fact that the schema might change after a document was ingested for this schema. In that case, the document would still use the most recent version of the schema, which might not work any longer for validating this document.
