### ISSUE TITLE
Schema validation

### ISSUE THREAD

**Issue by sabrineChe** [kit-data-manager/metastore2#35]
While ingesting a new schema, which includes no schema tag, the validation is passed. Otherwise, the validation failed while using the same schema for updating. Message Error is: `Unable to detect schema type automatically. Please provide a valid type`

Provided JSON Schema:
`{
    "type": "object",
    "properties": {
        "title": {
            "type": "string",
            "title": "Title",
            "description": "Title of object."
        }
    }
}`

**Comment by VolkerHartmann** [comment]
Should be fixed in the meantime. Unfortunately without explicit commit message.
