### ISSUE TITLE
Attribute 'locked' is not used.

### ISSUE THREAD

**Issue by VolkerHartmann** [kit-data-manager/metastore2#37]
Behaviour will not change if 'lock' is set to 'true'.

**Comment by ThomasJejkal** [comment]
It is used, not the purpose is another. The documentation states: 

"The schema can be synchronized from a central registry. If 'true', synchronization will be skipped."

and accordingly it is used in class:

edu.kit.datamanager.metastore2.service.SchemaSynchronizationService

**Comment by VolkerHartmann** [comment]
Then the label should possibly be chosen differently. A label with 2 different meanings easily leads to irritation. 
'sync' could be a better label.
