### ISSUE TITLE
Add AAI

### ISSUE THREAD

**Issue by VolkerHartmann** [kit-data-manager/metastore2#4]
To restrict access to authorized users, an AAI must be added.

**Comment by VolkerHartmann** [comment]
In the end it must also support [HIFIS](https://www.hifis.net/).

**Comment by ThomasJejkal** [comment]
Generally, authentication and user/group management is covered by the auth-service (https://github.com/kit-data-manager/auth-service). MetaStore2 will receive a Json Web Token with each call containing user and group information and can decide on its own on permissions. 

Regarding HIFIS integration and general access to the service an Entry-Point-Service (e.g. a UI) should be defined which can than be linked to HIFIS as well as to the auth-service. Resources regarding possible HIFIS integration con be found here: 

  * https://hifis.net/doc/service-integration/services/nextcloud/configuration/aai/ 
  * https://hifis.net/doc/core-services/aai-proxy/ 

A detailed description on service registration procedures and registering services in the Helmholtz Cloud will be available next year.
