### ISSUE TITLE
MetadataRecord 

### ISSUE THREAD

**Issue by nicolasblumenroehr** [kit-data-manager/metastore2#48]
Using the following metadata record (more than the mandatory fields) for metadata registration, the message "No valid metadata record provided" shows up:

{
    "relatedResource": {
        "identifier": "20211016_",
        "identifierType": "INTERNAL"
    },
    "createdAt": "20211019",
    "lastUpdate": "20211019",
    "schema": {
        "identifier": "Frictionless_DP_Schema",
        "identifierType": "INTERNAL"
    },
    "schemaVersion": 1,
    "recordVersion": 1,
    "metadataDocumentUri": "To be updated"
}

**Comment by ThomasJejkal** [comment]
I'm not totally sure, but try to skipt "createdAt" and "lastUpdate" or use the proper data-time-format like yyyy-MM-dd'T'HH:mm:ss'Z', e.g., 2021-10-19T15:18:00Z
