### ISSUE TITLE
Starting version 0.3.0 with Docker not possible

### ISSUE THREAD

**Issue by maximilianiKIT** [kit-data-manager/metastore2#49]
When I try to start the container with `docker run kitdm/metastore2:latest` or `docker run kited/metastore2` it throws this error and exit:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "bash": executable file not found in $PATH: unknown.`

I am using Docker version 20.10.8 on MacOS 11.6.

**Comment by VolkerHartmann** [comment]
Fixed with version 0.3.1
