### ISSUE TITLE
Incorrect Schema Version in the Metadata Record

### ISSUE THREAD

**Issue by sabrineChe** [kit-data-manager/metastore2#59]
**Describe the bug**
The schema version property in the metadata record is stored incorrectly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Register a schema with identifier "schema1"
2. Update "schema1"
2. Ingest a metadata document for "schema1", "version: 2"
3. While reading the metadata record, the "schema version" property is "1".

**Expected behavior**
The "schema version" property should be 2 as the user registered a metadata document for the 2nd version of "schema1".

**Screenshots**

<img width="515" alt="error" src="https://user-images.githubusercontent.com/69915427/144254882-ff5d38c7-5504-4316-8ff7-6d0642a2c77a.png">

**Comment by VolkerHartmann** [comment]
The schema version is already set to 1 at the first ingest, since URLs are unique and there cannot actually be 2 versions. Nevertheless, I will now adjust the version of the actual version for internally managed schemas.
