### ISSUE TITLE
GUI: List for schema show only 2 entries per page.

### ISSUE THREAD

**Issue by VolkerHartmann** [kit-data-manager/metastore2#66]
**Describe the bug**
Listing shows only 2 entries per page. May it be possible to change this.

**To Reproduce**
1. Register more than 2 schemas.
2. Go to ''http://localhost:8040/schema-management/

**Expected behavior**
There should be at least 10 entries per page. 
Even better it should be configurable.

**Comment by sabrineChe** [comment]
The pagination size is 2 entries per page. This will be changed to 10 entries per page. The possibility of the configuration of the pagination size will be made.
