### ISSUE TITLE
No of pages seems to be to wrong

### ISSUE THREAD

**Issue by VolkerHartmann** [kit-data-manager/metastore2#67]
**Describe the bug**
I created 8 entries. but listing shows 5 pages.

**To Reproduce**
1. Register 2 schemas.
2. Go to ''http://localhost:8040/schema-management/
3. There should be 2 pages listed at the bottom line.

**Expected behavior**
There should be only 1 page. 
![grafik](https://user-images.githubusercontent.com/14762686/149495280-3691aec1-485f-4a07-a0c0-e94851b424ee.png)

**Comment by sabrineChe** [comment]
The number of pages is directly generated by the tabulator library. Are the 8 entries listed correctly? Does the 5th page include any entry ?

**Comment by VolkerHartmann** [comment]
In the example above you are not able to select page 2. Nevertheless page 2 seems to be available. If you are not aware that there are only 2 entries this might be confusing. That's another reason why the total no of entries seems to be helpful.
