### ISSUE TITLE
Discussion: Labeling of button while 

### ISSUE THREAD

**Issue by VolkerHartmann** [kit-data-manager/metastore2#69]
**Describe the bug**
![grafik](https://user-images.githubusercontent.com/14762686/149497616-c2934f48-226d-4b3e-b72d-546292a29d5b.png)

**To Reproduce**
1. Register at least one schema.
2. Open schema management http://localhost:8040/schema-management
3. Click on the eye to see all metadata of the entry. (This will open a dialog like the one you see above.)
4. Click on schema below.
5. This opens a form for the metadata and not for the schema.

**Expected behavior**
As button is labeled with schema I would expect to edit the schema instead of creating a document valid to the selected schema.

May be button should be labeled with 'Register Metadata Document'

**Comment by sabrineChe** [comment]
While clicking on the button "schema", the user should be able only to read the schema and not to register a metadata document. With the eye icon, the user is able to read the schema record and when clicking on the button "schema" he is able to read the schema itself. 
To register a new metadata document, the user has to click on the listing icon of a specific schema or to open the metadata management page.
