### ISSUE TITLE
Permission check inconsistent

### ISSUE THREAD

**Issue by ThomasJejkal** [kit-data-manager/metastore2#71]
**Describe the bug**
Permission check in the controller seems to be inconsistent. This was tested with the SchemaRegistryController, but probably also applies to the MetadataController. The point is, that listing all resources via `/api/v1/schemas/` works without restriction. By using this endpoint, one can list all schemas independent of authorization information. However, as soon as one tries to access a single resource from this listing via `/api/v1/schemas/{schemaId}`, a permission check for READ permission is applied and access will fail. 

**To Reproduce**
1. Use a MetaStore instance with enabled security
2. Add resources with different ACL information
3. Access `/api/v1/schemas/` -> returns all schemas
4. Access `/api/v1/schemas/{schemaId}` with `schemaId` pointing to a schema without READ permissions for the caller -> fails with HTTP 403

**Expected behavior**
Step 3 and 4 should handle access consistently. As READ access is explicitly required for GET operations, listing should also include ACL filtering.

**Comment by ThomasJejkal** [comment]
After stumbling again over this issue, are there plans to tackle this until 1.0.0? In DataResourceService, [SpecUtils.getByExampleSpec](https://github.com/kit-data-manager/repo-core/blob/0262fccabe3fe37e257b72f7f352461ddf49a6fe/src/main/java/edu/kit/datamanager/repo/util/SpecUtils.java#L43) is used to include SIDs and required permission. Thus this should be also possible in getRecords.

**Comment by VolkerHartmann** [comment]
This should be already solved: https://github.com/VolkerHartmann/metastore2/commit/cd33cee44bf0207aec811ecef0c2b399933ae453
Just waiting for next release.
