### ISSUE TITLE
Returning all resources of a specific schema

### ISSUE THREAD

**Issue by sabrineChe** [kit-data-manager/metastore2#74]
**Is your feature request related to a problem? Please describe.**
I registered two versions of my JSON schema and  ingested one resource for each version of the schema. I want to list all resources of both versions of my schema by calling the following GET operation `/api/v1/metadata?schemaId={schema}` . However, i get only the resource of the latest version of my schema.

**Describe the solution you'd like**
I want to get all resources for both versions of my schema.

**Comment by VolkerHartmann** [comment]
Which version are you using? It should be fixed for a while.
I tested it with version 0.3.7 and the newest development branch and it works as expected. 
Could you please test once more with at least version 0.3.7.
