### ISSUE TITLE
JSON Metadata Document Validation failed

### ISSUE THREAD

**Issue by sabrineChe** [kit-data-manager/metastore2#77]
**Describe the bug**
I register the following JSON schema `{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://www.example.org/schema/json",
    "type": "object",
    "properties": {
        "seriesArray": {
            "title": "Series array",
            "type": "array",
            "minItems": 1,
            "items": {
            	"type": "object",
                "properties": {
                	"studyName": {
                		"title": "Study name",
                		 "description": "Name of the study",
                		 "type": "string"
                	}
                }
          }
       }
   }
}
`
I try after to ingest the following Metadata Document for this schema `{"seriesArray":[{"studyName": "study"}]}`
Unfortunately, the Metadata Validation failed.

**To Reproduce**
1. Register the JSON Schema
2. Ingest the Metadata Document
3. Error: `Could not load validator minItems, com.networknt.schema.JsonSchemaException: java.lang.NoSuchMethodError: 'boolean com.fasterxml.jackson.databind.JsonNode.canConvertToExactIntegral()'`

**Expected behavior**
The Metadata Document should be validated against the schema and ingested.

**Additional context**
I think the issue is concerning the used JSON Validator. It can not validate the attribute "minItems". When deleting this attribute, the validation of the metadata document works.

**Comment by VolkerHartmann** [comment]
Unfortunately there is an error(?) in the library we use. Can not exactly locate it. 
Right now the solution is to switch back to version 1.0.43 of library  com.networknt:json-schema-validator. :-(
