### ISSUE TITLE
Update Metadata Schema Record

### ISSUE THREAD

**Issue by sabrineChe** [kit-data-manager/metastore2#78]
**Describe the bug**
I register a JSON schema. After, i try to update the type in the Metadata Schema Record from "json" to "xml".

**To Reproduce**
1. Register JSON Schema 
2. Update the type property in the record from "json" to "xml"
3. The update operation is executed correctly, which should not be the case as i did not update my JSON schema

**Expected behavior**
An exception should be shown to the user.

**Comment by VolkerHartmann** [comment]
You are right. I will fix it.
