### ISSUE TITLE
Authentication seems to be mandatory 

### ISSUE THREAD

**Issue by VolkerHartmann** [kit-data-manager/metastore2#83]
**Describe the bug**
Authentication is disabled by default. Nevertheless a login window appears while trying to list all schemas.

**To Reproduce**
1. Go to 'http://localhost:8040'
2. Click on 'Schema Management.'
3. See login window

**Expected behavior**
There should be no login window if authentication is disabled and/or the possibility to login as 
a guest.

**Screenshots**
![image](https://user-images.githubusercontent.com/14762686/158009273-f341e9cb-fc7f-459a-a565-f7d7fe5161ac.png)

For test use this code: https://github.com/VolkerHartmann/metastore2/tree/forTestOnly

**Comment by ThomasJejkal** [comment]
Well, unfortunately for the GUI there is no way to access any information whether auth is enabled or disabled. Due to the close integration into MetaStore it has to be build either with our without authentication enabled.
