### ISSUE TITLE
Provide some examples

### ISSUE THREAD

**Issue by geyslein** [kit-data-manager/metastore2#86]
As a user, in order to test the application and the api I would like to have a real world example of an existing metadata schema (json+xml) and a single metadata file to test against.
It would help to understand what purpose metastore2 serves and inspire others to add other metadata schemas to validate.

**Comment by VolkerHartmann** [comment]
We appreciate the hint.
At the moment we are preparing version 1.0.0. This will contain a GUI that will simplify the handling very much. We are aware that good documentation is still missing and will provide it soon.

Until then, you must use the following links:
- https://github.com/kit-data-manager/metastore2/blob/master/restDocu.md
or if a (local) MetaStore instance is running: 
- http://localhost:8040/swagger-ui.html
- http://localhost:8040/static/docs/documentation.html

**Comment by geyslein** [comment]
Thanks a lot for the coming update. Technically I get along with the documentation, the swagger thing helps a lot. Actually I was talking about an example of a schema implementation of an existing standard in metastore. Maybe sth. that you are familiar with. Some use-case szenarios would be also highly appreciated.

**Comment by ThomasJejkal** [comment]
I'm not totally sure what you mean by

> example of a schema implementation of an existing standard in metastore

I think we agree, that schema is the technical realization of a standard, i.e., DataCite is the standard, which has (at least) two realizations: one as XSD schema and one as JSON schema. The creation of such schemas is not in the scope of MetaStore. Instead, if you have such a schema (either provided by the standard's owner or self-created) you can register it at MetaStore and you can manage metadata documents for a registered schema, e.g. create, read, find, validate, update, etc.

I've just finished a (very basic) tutorial showing the first steps while using MetaStore. You can find the tutorial at [Katacoda](https://www.katacoda.com/kitdm/scenarios/metastore). I hope this helps.

**Comment by VolkerHartmann** [comment]
Unfortunately katacoda is no longer available.
Maybe this [cookbook](https://kit-data-manager.github.io/metastore2/schema/introduction.html) might help.
***Attention:*** The provided UI is no longer maintained. Please take a look at this [external UI](https://github.com/kit-data-manager/frontend-collection) for MetaStore which behaves nearly similar and also supports authentication via keycloak out of the box.
